### ISSUE TITLE
Introduce URL params for filter

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#12]
- [x] checking a filter should accordingly update url
- [x] pass on table identifier for multi table page solution
- [x] apply url filters on loading of table via php for optimal performance
- [x] Right filter checkboxes should be checked right away

**Comment by eynimeni** [comment]
filter params should be reset on table (tab) change
![Screenshot 2023-04-28 at 10 16 04](https://user-images.githubusercontent.com/78353570/235093955-e6ee8070-4d3f-42c7-9be6-992e7a0d7693.png)

**Comment by eynimeni** [comment]
only append filter etc param to url if != null
