### ISSUE TITLE
Warning on /admin/webservice/testclient.php

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#15]
External function parameters: invalid OPTIONAL value specified.

    line 729 of /lib/externallib.php: call to debugging()
    line 63 of /local/wunderbyte_table/classes/external/execute_action.php: call to external_function_parameters->__construct()
    line 122 of /lib/externallib.php: call to local_wunderbyte_table\external\execute_action::execute_parameters()
    line 52 of /admin/webservice/testclient.php: call to external_api::external_function_info()

External function parameters: invalid OPTIONAL value specified.

    line 729 of /lib/externallib.php: call to debugging()
    line 58 of /mod/booking/classes/external/load_pre_booking_page.php: call to external_function_parameters->__construct()
    line 122 of /lib/externallib.php: call to mod_booking\external\load_pre_booking_page::execute_parameters()
    line 52 of /admin/webservice/testclient.php: call to external_api::external_function_info()

External function parameters: invalid OPTIONAL value specified.

    line 729 of /lib/externallib.php: call to debugging()
    line 46 of /user/profile/field/conditional/classes/external.php: call to external_function_parameters->__construct()
    line 122 of /lib/externallib.php: call to profilefield_conditional\external::get_other_fields_parameters()
    line 52 of /admin/webservice/testclient.php: call to external_api::external_function_info()

**Comment by georgmaisser** [comment]
Fixed 3aa4b6a531c4913b42fe1556903bfa11cb149288
