### ISSUE TITLE
styles.css not specfic enough.

### ISSUE THREAD

**Issue by danmarsden** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#34]
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/blob/main/styles.css#L303C1-L319

https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/blob/main/styles.css#L405-L407

(and possibly others)

in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code  - note this is usually a blocker as it's really hard for people to diagnose when a plugin interferes with core css.

**Comment by danmarsden** [comment]
definitely looking a lot better but these 2 are still quite generic and could clash with standard moodle:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/blob/main/styles.css#L299-L304

https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/blob/main/styles.css#L310-L312

**Comment by georgmaisser** [comment]
Hi @danmarsden , Thank you so much for your last feedback, we should have caught that right away. We will resubmit the plugin with the latests changes, they are already implemented and pushed to the main branch.

As of our other Plugins, especially local_shopping_cart, we will take a hard look ourselves and ping you in January, so we are sure that you don't have too much work telling us obvious mistakes. I am sure you will find enough anyways... ;-)

**Comment by danmarsden** [comment]
thanks @georgmaisser - once you've updated the plugins db with this latest release, ping me on the moodle tracker issue again and this should be ready to go - thanks!
