### ISSUE TITLE
no logging implemented

### ISSUE THREAD

**Issue by danmarsden** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#40]
Ideally you should have some event logging in this plugin - allowing the admin/user to see when a user has viewed/accesed/downloaded a report.

not a blocker for approval - just would be nice to have.

**Comment by georgmaisser** [comment]
Hi @danmarsden , we started working on all the issues you raised right away. Just one thing: We have submitted a few more plugins and I guess some of them will have similar issues. So, I guess it would be better to temporarily hold back, especially on local_shopping_cart, until we have fixed those issues. That way, you won't run into unnecessary work. Thanks!
