### ISSUE TITLE
allowsearchincolumns language translation issue

### ISSUE THREAD

**Issue by gjb2048** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#51]
Which is:

![Screenshot 2024-03-07 175248](https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/assets/1058419/809f65c0-de66-4e17-93a4-5796e7916ff3)

In the English language file: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/blob/f1a42fce2d0ac7deba47f882ea40bd14b2f535db/lang/en/local_wunderbyte_table.php#L110

Version https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/commit/f1a42fce2d0ac7deba47f882ea40bd14b2f535db

**Comment by bernhard-wunderbyte** [comment]
Fixed.
