### ISSUE TITLE
Error when trying to add a websersive in Moodle

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#60]
How to reproduce:

- Go to Site admin -> Server -> Webservice
- Create a new external service (only allowed users)
- Add capability: delete users
- Add a function

Result: 

`Coding error detected, it must be fixed by a programmer: Cannot find file [dirroot]/local/wunderbyte_table/externallib.php with external function implementation for local_wunderbyte_table\external\sort_rows::execute`

Moodle version 4.1.11+
wb table: 2.0.6

**Comment by georgmaisser** [comment]
Thank you for reporting. Fixed here: 95aa816bc4de72c2dd405e9f7202bfccd956f882

We have updated the main branch.
