### ISSUE TITLE
Testing Filter: Explode Filter & filtercounter

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#65]
There is a new type of filter for wb_table that explodes values.
So for data like:
<img width="85" alt="Screenshot 2024-10-16 at 11 20 20" src="https://github.com/user-attachments/assets/998cad09-7586-4bb0-a170-cd455ff9134f">
When filter is defined like:
![Screenshot 2024-10-16 at 11 51 53](https://github.com/user-attachments/assets/48aee6c5-f1a4-4896-903d-d3fa68f01f3b)
It should be displayed like:
![Screenshot 2024-10-16 at 11 20 26](https://github.com/user-attachments/assets/e78fe5a5-a831-47fa-9a51-ea203a4074f7)

I have added the filter to demo (as in screenshot) and started integration of test
- [ ] since I have problems running behat locally, could you please have a look and improve the test if problems are given?
- [ ] It seems important, that also the filtercountlabel - showing the number of records found - is available and correctly displayed
- [ ] Also the filtercounter badge should be displayed correctly, showing how many filters are active 
(3 in this example) 
![Screenshot 2024-10-16 at 12 19 25](https://github.com/user-attachments/assets/7130cbbb-40c2-4d56-b3f5-77fac7ed7f36)

- [ ] Extend tests for hierarchical filter (like in demo table 1 firstname)

- [ ] Extend tests (if not already given)for the filtercountlabel &  filtercounter badge also in other filters (i.e. username)

- [ ] datepicker, timespan, intrange filter will display (1) as filtercounter badge if active

**Comment by semteacher** [comment]
@eynimeni 
At the moment I see 1 bug: those items which givent custom label display count less by 1 than really are
![image](https://github.com/user-attachments/assets/ddeef259-61ba-4c90-a786-5ae985343ac1)
(I mean - filter working properly and process proper amount ofrecord. But in drop-down - count has value decreased by 1) 
Have tried to debug but failed. Generally it has to be related to https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/commit/5915a7ff02ddf79813317b09087aa2a60565afc7#diff-11d78aa2387db7662f046622344201745a9cd77fe6f0d8db80c2871f535cbdeeL274

**Comment by eynimeni** [comment]
that is interesting and I think it is related to the data in the database because with my data it's working well
![Screenshot 2024-10-17 at 09 08 25](https://github.com/user-attachments/assets/79a92480-e551-43b9-982e-6337b37213af)

**Comment by semteacher** [comment]
@eynimeni I also  faced the following error:
![image](https://github.com/user-attachments/assets/3594fb0d-5576-4336-9c38-843250db80c5)
does it because of filtering by int ID value ?

**Comment by semteacher** [comment]
Speaking of item count... after more testing I found
- definition like 
![image](https://github.com/user-attachments/assets/c195b399-9566-40e8-b6d2-7e16a2e67ff7)
produce correct counts.
![image](https://github.com/user-attachments/assets/a82f6b31-99e9-42d5-8e69-36505c21726f)
- but definition like
![image](https://github.com/user-attachments/assets/9126c718-31b3-4789-bb1b-7d7954b9e839)
lead to incorrect counts
![image](https://github.com/user-attachments/assets/a7cecc56-4b2b-4e5c-b10a-8a91c3f9c8da)

It seems than 2 identical values in depatement field being processed only once

- so I have added 3rd duplication
![image](https://github.com/user-attachments/assets/84012d3e-3246-4926-8588-62c4d7c78726)
- and got even lover counts
![image](https://github.com/user-attachments/assets/64f38d20-dc98-4aeb-a40f-712cc7bdb7a1)

**Comment by semteacher** [comment]
Fixed https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/issues/65#issuecomment-2422779585

**Comment by semteacher** [comment]
Got this counts under MariaDB/MySQL
![image](https://github.com/user-attachments/assets/0fd59254-d44e-4652-85bc-77a61fec9ccd)

**Comment by semteacher** [comment]
Have fixed issue with MySQL too. 
But https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/issues/65#issuecomment-2422758720 remains.
I think that problem is in the apply_filter() methid of the standardfilter class.

**Comment by eynimeni** [comment]
@semteacher thank you for pointing this out. should be fixed with previous commit. 
could you please confirm and close the issue, if no more bugs remain?

**Comment by semteacher** [comment]
@eynimeni Yes, issue with ID filter has been fixed.
